version: '3.8'

services:
  postgres:
    image: postgres
    #    build:
    #      context: services/postgres
    #      dockerfile: Dockerfile.development
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=apinews
      - POSTGRES_PASSWORD=123
#    volumes:
#      - "db-data:/var/lib/postgresql/data"
  app:
    image: denisiskhakov/postgresdockercompose
    #    build: .
#      context: services/app
#      dockerfile: Dockerfile.development

    environment:
      #      - PORT=8091
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/apinews
#    image: 'my-java-app'
    ports:
      - 8080:8080
    depends_on:
      - postgres

#volumes:
#  db-data: